### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by lilit-rande** [leny/atom-pane-layout-switcher#4]
In keymaps/pane-layout-switcher.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by leny** [comment]
Hi, thanks for the report. 

It has been fixed & published as version `0.0.3`.

But this package is kinda like "dropped" in favor of the more complete [pane-manager](https://atom.io/packages/pane-manager) package.
