### ISSUE TITLE
Disabled by v0.206

### ISSUE THREAD

**Issue by dsandstrom** [leny/atom-pane-layout-switcher#5]
The package is using deprecated API so it's disabled by default.

`workspaceView` is deprecated, but there might be others.

**Comment by leny** [comment]
Hum... strange, I had published a fix for deprecations a week ago and this deprecation has not been raised... I'll take a look.

Thanks for the report.

**Comment by leny** [comment]
No, sorry : this package has been deprecated in favor of [atom-pane-manager](https://atom.io/packages/pane-manager).

I will unpublish it.

**Comment by dsandstrom** [comment]
Thanks, switched to that one.  You might want to do the same for inc-dec-value.
